**Loading the dataset**
We use the *pickle* library to read the data.

In [4]:
def unpickle(filename):
    import pickle
    with open(filename, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [ ]:
def data_loss(x, W, y):
    '''Computes the SVM loss using a linear classifier.
    W --> A (10x3073) Weight Matrix including the bias term
    x --> A matrix in which each image of the training set is flattened out as a column vector. 
        Hence, if the dataset has 10,000 images, x is a (3073 x 10000) matrix
    y --> Index of true class label values between 0 to 9 representing each of the 10 classes of CIFAR-10. This will be a 
        (1x10000) row vector'''
    
    # Computing the scores
    scores = np.dot(W, x) # scores will be a (10x10000) matrix representing score for each class for each training example.
    
    for i in range(10000):
        scores[:, i] = scores[:, i] - scores[y[i], i] + 1

    loss_i = np.sum(np.maximum(0,scores)/10000)
    return loss_i

In [ ]:
def regularization_loss(W):
    return np.sum(np.square(W))

Loading the first batch and exploring the dataset.

In [8]:
data = unpickle('cifar-10-batches-py/data_batch_1')
print(data.keys())
print('Total number of labels: ', len(data[b'labels']))
print('Datatype of labels: ', type(data[b'labels']))
print('First five labels:', data[b'labels'][:5])
print('\n')

print(len(data[b'data']))
print(type(data[b'data']))
print(data[b'data'].shape)
print(data[b'data'][:5])

dict_keys([b'batch_label', b'labels', b'data', b'filenames'])
Total number of labels:  10000
Datatype of labels:  <class 'list'>
First five labels: [6, 9, 9, 4, 1]


10000
<class 'numpy.ndarray'>
(10000, 3072)
[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 [ 28  37  38 ...  28  37  46]
 [170 168 177 ...  82  78  80]]


In [10]:
import numpy as np

In [32]:
temp = np.array([[1,2,3,4],[10,20,30,40], [100,200,300,400]])
print(temp)
print('\n\n')

b = [1,2,0,1]
for i in range(4):
    temp[:, i] = temp[:, i] - temp[b[i], i]
print(temp)
print('\n\n')
print(np.maximum(0, temp))

print('\n\n')
print(np.sum(np.maximum(0, temp)))

[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]]



[[  -9 -198    0  -36]
 [   0 -180   27    0]
 [  90    0  297  360]]



[[  0   0   0   0]
 [  0   0  27   0]
 [ 90   0 297 360]]



774


In [35]:
np.sum(np.square(temp))

299619